export const GET_NOTIFICATIONS = '[NOTI] GET_NOTIFICATIONS' as const;
export const GET_NOTIFICATIONS_CANCEL = '[NOTI] GET_NOTIFICATIONS_CANCEL' as const;
export const GET_NOTIFICATIONS_FAILURE = '[NOTI] GET_NOTIFICATIONS_FAILURE' as const;
export const GET_NOTIFICATIONS_REQUEST = '[NOTI] GET_NOTIFICATIONS_REQUEST' as const;
export const GET_NOTIFICATIONS_SUCCESS = '[NOTI] GET_NOTIFICATIONS_SUCCESS' as const;
export const GET_NOTIFICATIONS_UPSERT = '[NOTI] GET_NOTIFICATIONS_UPSERT' as const;

export const GET_UNREAD_COUNT = '[NOTI] GET_UNREAD_COUNT' as const;
export const GET_UNREAD_COUNT_CANCEL = '[NOTI] GET_UNREAD_COUNT_CANCEL' as const;
export const GET_UNREAD_COUNT_FAILURE = '[NOTI] GET_UNREAD_COUNT_FAILURE' as const;
export const GET_UNREAD_COUNT_REQUEST = '[NOTI] GET_UNREAD_COUNT_REQUEST' as const;
export const GET_UNREAD_COUNT_SUCCESS = '[NOTI] GET_UNREAD_COUNT_SUCCESS' as const;
