export const GET_ME_PROFILE_SKIP = '[ME] GET_ME_PROFILE_SKIP';
export const GET_ME_PROFILE_REQUEST = '[ME] GET_ME_PROFILE_REQUEST';
export const GET_ME_PROFILE_SUCCESS = '[ME] GET_ME_PROFILE_SUCCESS';
export const GET_ME_PROFILE_FAILURE = '[ME] GET_ME_PROFILE_FAILURE';
export const GET_ME_PROFILE_CANCELLED = '[ME] GET_ME_PROFILE_CANCELLED';

export const PUT_ME_FOLLOW_STATE_SUCCESS = '[ME] PUT_ME_FOLLOW_STATE_SUCCESS';
export const PUT_ME_FOLLOW_STATE_SKIP = '[ME] PUT_ME_FOLLOW_STATE_SKIP';
export const REFRESH_ME_FOLLOW_STATE = '[ME] REFRESH_ME_FOLLOW_STATE';
