import pathnamePairs from './pathnames';

export default {
  feed: [
    pathnamePairs.root,
    pathnamePairs.feed,
    pathnamePairs.meMessages,
    pathnamePairs.meNotifications,
    // '/my-home',
    // '/[look]',
    // '/[look]/edit',
    // '/upload',
    // '/me/upload',
    // '/collections/[id]',
    // '/collections/new',
    // '/articles/[id]',
    // '/+articles/[id]',
    // '/featured-collections',
    // '/settings/sns',
    // '/settings/password',
    // '/settings/profile',
  ],
  none: [
    // '/intro',
    // '/login',
    // '/join',
    // '/privacy',
    // '/privacy/[locale]',
    // '/terms-of-use',
    // '/terms-of-use/[locale]',
    // '/content-guidelines',
    // '/content-guidelines/[locale]',
    // '/notices',
    // '/notice/[id]',
  ],
  store: [
    pathnamePairs.category,
    pathnamePairs.categoryBest,
    pathnamePairs.categoryDetail,
    pathnamePairs.goodsDetail,
    pathnamePairs.goodsDetailStyles,
    pathnamePairs.store,
    // '/brands',
    // '/brands/[id]',
    // '/catalogs/[id]',
    // '/me/cart',
    // '/me/point',
    // '/order/history',
    // '/order/history/[id]',
  ],
};
